config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, only: [:new, :create, :edit, :update]
  resources :customers
  resources :user_infos, only: [:new, :create]
  resources :brands
  resources :customer_notes
  resources :email_templates
  resources :customer_emails
  get "projects/:project_id/brands/:brand_id", to: "projects#show"

  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :projects
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    resources :email_templates
  end
end

app/models/project.rb
class Project < ApplicationRecord
  before_create :create_code

  validates :name, presence: true
  validates :address, presence: true
  validates :investor, presence: true
  validates :constructor, presence:true

  has_attached_file :logo
  validates_attachment_content_type :logo, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

  private

    def create_code
      self.code = SecureRandom.urlsafe_base64
    end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :admin_must_logged_in
  layout "admin"

  def index
    @projects = Project.paginate(page: params[:page])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.valid?
      @project.save
      flash[:success] = "Create successfully"
      redirect_to admin_projects_path
    else
      render "new"
    end
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    if @project.update project_params
      flash[:success] = "Project was updated successfully"
      redirect_to edit_admin_project_path(@project)
    else
      render "edit"
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project deleted"
    redirect_to admin_projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :address, :investor,
                                      :constructor, :logo, :info)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout false

  def show
    @project = Project.find_by(id: params[:project_id])
    @brand = Brand.find_by(id: params[:brand_id])
  end
end

app/views/admin/projects/edit.html.haml
- provide(:active, "project")
%section.forms
  .container-fluid
    .row
      .col-lg-12
        .card
          .card-header.d-flex.align-items-center
            %h3.h4= @project.name
          .card-body
            = render "shared/error_messages", object: @project
            = form_for(@project, url: admin_project_path(@project)) do |f|
              .form-group
                %label.form-control-label Tên dự án
                = f.text_field :name, class: "form-control"
              .form-group
                %label.form-control-label Địa chỉ
                = f.text_field :address, class: "form-control"
              .form-group
                %label.form-control-label Chủ thầu
                = f.text_field :investor, class: "form-control"
              .form-group
                %label.form-control-label Chủ thi công
                = f.text_field :constructor, class: "form-control"
              .form-group
                %label.form-control-label Thông tin
                = f.text_area :info, class: "form-control"
              .form-group
                %label.form-control-label Anh dai dien
                - if @project.logo
                  %div
                    %img{ src: @project.logo.url, width: 55, height: 55}
                  %br
                .col-sm-12
                  = f.file_field :logo
              .line
              .form-group
                .pull-right
                  %button.btn.btn-success Lưu thay đổi

app/views/admin/projects/index.html.haml
- provide(:active, "project")
%section.tables
  .container-fluid
    .row
      .col-lg-12
        = will_paginate @projects
        .card
          .card-header.d-flex.align-items-center
            %h3.h4 Danh sách khách hàng
          .card-body
            %table.table
              %thead
                %th Tên
                %th Ảnh
                %th Địa chỉ
                %th Chủ đầu tư
                %th Chủ thi công
                %th Thông tin
              %tbody
                - @projects.each do |project|
                  %tr
                    %td
                      %a{ href: edit_admin_project_path(project) }
                        = project.name
                    %td
                      - if project.logo
                        %img{ src: project.logo.url, widht: 55, height: 55 }
                    %td= project.address
                    %td= project.investor
                    %td= project.constructor
                    %td
                      %a.btn.btn-sm.btn-info{ href: edit_admin_project_path(project) }
                        %span.fa.fa-pencil
                        Edit
        = will_paginate @projects

app/views/admin/projects/new.html.haml
- provide(:active, "project")
%section.forms
  .container-fluid
    .row
      .col-lg-12
        .card
          .card-header.d-flex.align-items-center
            %h3.h4 Tạo mới dự án
          .card-body
            = render "shared/error_messages", object: @project
            = form_for(@project, url: admin_projects_path) do |f|
              .form-group
                %label.form-control-label Tên dự án
                = f.text_field :name, class: "form-control"
              .form-group
                %label.form-control-label Địa chỉ
                = f.text_field :address, class: "form-control"
              .form-group
                %label.form-control-label Chủ thầu
                = f.text_field :investor, class: "form-control"
              .form-group
                %label.form-control-label Chủ thi công
                = f.text_field :constructor, class: "form-control"
              .form-group
                %label.form-control-label Thông tin
                = f.text_area :info, class: "form-control"
              .form-group
                %label.form-control-label Anh dai dien
                .col-sm-9
                  = f.file_field :logo
              .line
              .form-group
                .pull-right
                  %button.btn.btn-success Tạo