config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, only: [:new, :create, :edit, :update]
  resources :customers
  resources :user_infos, only: [:new, :create]
  resources :brands
  resources :customer_notes
  resources :email_templates
  resources :customer_emails
  get "projects/:project_id/brands/:brand_id", to: "projects#show"

  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :projects
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    resources :email_templates
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true
  has_attached_file :logo
  validates_attachment :logo, presence: true,
    size: { in: 0..5.megabytes }
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :user_must_logged_in

  def edit
    @brand = Brand.find params[:id]
  end

  def update
    @brand = Brand.find params[:id]
    if @brand.update brand_params
      flash[:success] = "Update successfully"
      redirect_to root_path
    else
      render "edit"
    end
  end

  private
    def brand_params
      params.require(:brand).permit(:name, :hot_line, :logo, :info)
    end
end

app/views/brands/edit.html.haml
%section.forms
  .container-fluid
    .row
      .col-lg-12
        .card
          .card-header.d-flex.align-items-center
            %h3.h4 Thông tin tài khoản
          .card-body
            = render "shared/error_messages", object: @brand
            = form_for(@brand, url: brand_path(@brand), html: { multipart: true }) do |f|
              .form-group-material
                = f.text_field :name, class: "form-control", placeholder: "Name"
              .form-group-material
                = f.text_field :hot_line, class: "form-control", placeholder: "Hot line"
              .form-group
                = f.text_area :info, class: "form-control", placeholder: "Thong tin ca nhan"
              .form-group.row
                %label.col-sm-3.form-control-label Anh dai dien
                .col-sm-9
                  = f.file_field :logo
              .line
              .form-group
                .pull-right
                  %button.btn.btn-success Save changes